/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.validation;

import org.fil2018.flomira.validation.AbstractSuricateValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SuricateValidator extends AbstractSuricateValidator {
}
