/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.tests;

import org.fil2018.flomira.suricate.Programme;
import org.fil2018.flomira.tests.SuricateInjectorProvider;
import org.junit.Test;
import org.junit.runner.RunWith;

/* @RunWith(/* name is null */)
@InjectWith(SuricateInjectorProvider.class) */@SuppressWarnings("all")
public class SuricateParsingTest {
  /* @Inject
   */private /* ParseHelper<Programme> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field SuricateParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
