/*
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSuricateValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.fil2018.flomira.suricate.SuricatePackage.eINSTANCE);
		return result;
	}
	
}
