/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.suricate;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Appel Methode</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fil2018.flomira.suricate.AppelMethode#getIfBody <em>If Body</em>}</li>
 * </ul>
 *
 * @see org.fil2018.flomira.suricate.SuricatePackage#getAppelMethode()
 * @model
 * @generated
 */
public interface AppelMethode extends Instruction, IfBoucle
{
  /**
   * Returns the value of the '<em><b>If Body</b></em>' containment reference list.
   * The list contents are of type {@link org.fil2018.flomira.suricate.Ligne}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>If Body</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>If Body</em>' containment reference list.
   * @see org.fil2018.flomira.suricate.SuricatePackage#getAppelMethode_IfBody()
   * @model containment="true"
   * @generated
   */
  EList<Ligne> getIfBody();

} // AppelMethode
