/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.suricate;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boucle</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.fil2018.flomira.suricate.SuricatePackage#getBoucle()
 * @model
 * @generated
 */
public interface Boucle extends Instruction
{
} // Boucle
