/**
 * generated by Xtext 2.10.0
 */
package org.fil2018.flomira.suricate;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fil2018.flomira.suricate.IntLiteral#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.fil2018.flomira.suricate.SuricatePackage#getIntLiteral()
 * @model
 * @generated
 */
public interface IntLiteral extends Objet
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(int)
   * @see org.fil2018.flomira.suricate.SuricatePackage#getIntLiteral_Name()
   * @model
   * @generated
   */
  int getName();

  /**
   * Sets the value of the '{@link org.fil2018.flomira.suricate.IntLiteral#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(int value);

} // IntLiteral
