/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.suricate;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Methode</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fil2018.flomira.suricate.Methode#getPara <em>Para</em>}</li>
 * </ul>
 *
 * @see org.fil2018.flomira.suricate.SuricatePackage#getMethode()
 * @model
 * @generated
 */
public interface Methode extends EObject
{
  /**
   * Returns the value of the '<em><b>Para</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Para</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Para</em>' containment reference.
   * @see #setPara(Parametre)
   * @see org.fil2018.flomira.suricate.SuricatePackage#getMethode_Para()
   * @model containment="true"
   * @generated
   */
  Parametre getPara();

  /**
   * Sets the value of the '{@link org.fil2018.flomira.suricate.Methode#getPara <em>Para</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Para</em>' containment reference.
   * @see #getPara()
   * @generated
   */
  void setPara(Parametre value);

} // Methode
