/**
 * generated by Xtext 2.10.0
 */
package org.fil2018.flomira.suricate;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Objet</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.fil2018.flomira.suricate.SuricatePackage#getObjet()
 * @model
 * @generated
 */
public interface Objet extends Parametre
{
} // Objet
