/**
 * generated by Xtext 2.10.0
 */
package org.fil2018.flomira.suricate;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fil2018.flomira.suricate.Operation#getName <em>Name</em>}</li>
 *   <li>{@link org.fil2018.flomira.suricate.Operation#getMethode <em>Methode</em>}</li>
 * </ul>
 *
 * @see org.fil2018.flomira.suricate.SuricatePackage#getOperation()
 * @model
 * @generated
 */
public interface Operation extends Ligne, Objet
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(Variable)
   * @see org.fil2018.flomira.suricate.SuricatePackage#getOperation_Name()
   * @model
   * @generated
   */
  Variable getName();

  /**
   * Sets the value of the '{@link org.fil2018.flomira.suricate.Operation#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(Variable value);

  /**
   * Returns the value of the '<em><b>Methode</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Methode</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Methode</em>' containment reference.
   * @see #setMethode(Methode)
   * @see org.fil2018.flomira.suricate.SuricatePackage#getOperation_Methode()
   * @model containment="true"
   * @generated
   */
  Methode getMethode();

  /**
   * Sets the value of the '{@link org.fil2018.flomira.suricate.Operation#getMethode <em>Methode</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Methode</em>' containment reference.
   * @see #getMethode()
   * @generated
   */
  void setMethode(Methode value);

} // Operation
