/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.suricate;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.fil2018.flomira.suricate.SuricatePackage
 * @generated
 */
public interface SuricateFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SuricateFactory eINSTANCE = org.fil2018.flomira.suricate.impl.SuricateFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Programme</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Programme</em>'.
   * @generated
   */
  Programme createProgramme();

  /**
   * Returns a new object of class '<em>Ligne</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ligne</em>'.
   * @generated
   */
  Ligne createLigne();

  /**
   * Returns a new object of class '<em>Affectation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Affectation</em>'.
   * @generated
   */
  Affectation createAffectation();

  /**
   * Returns a new object of class '<em>Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instruction</em>'.
   * @generated
   */
  Instruction createInstruction();

  /**
   * Returns a new object of class '<em>Boucle</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boucle</em>'.
   * @generated
   */
  Boucle createBoucle();

  /**
   * Returns a new object of class '<em>If Boucle</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>If Boucle</em>'.
   * @generated
   */
  IfBoucle createIfBoucle();

  /**
   * Returns a new object of class '<em>Appel Methode</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Appel Methode</em>'.
   * @generated
   */
  AppelMethode createAppelMethode();

  /**
   * Returns a new object of class '<em>Appel Meth Composite</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Appel Meth Composite</em>'.
   * @generated
   */
  AppelMethComposite createAppelMethComposite();

  /**
   * Returns a new object of class '<em>Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable</em>'.
   * @generated
   */
  Variable createVariable();

  /**
   * Returns a new object of class '<em>Appel Meth Simple</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Appel Meth Simple</em>'.
   * @generated
   */
  AppelMethSimple createAppelMethSimple();

  /**
   * Returns a new object of class '<em>Parametre</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parametre</em>'.
   * @generated
   */
  Parametre createParametre();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SuricatePackage getSuricatePackage();

} //SuricateFactory
