/**
 * generated by Xtext 2.10.0
 */
package org.fil2018.flomira.suricate;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.fil2018.flomira.suricate.SuricateFactory
 * @model kind="package"
 * @generated
 */
public interface SuricatePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "suricate";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.fil2018.org/flomira/Suricate";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "suricate";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SuricatePackage eINSTANCE = org.fil2018.flomira.suricate.impl.SuricatePackageImpl.init();

  /**
   * The meta object id for the '{@link org.fil2018.flomira.suricate.impl.ProgrammeImpl <em>Programme</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.fil2018.flomira.suricate.impl.ProgrammeImpl
   * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getProgramme()
   * @generated
   */
  int PROGRAMME = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMME__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Programme</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.fil2018.flomira.suricate.impl.LigneImpl <em>Ligne</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.fil2018.flomira.suricate.impl.LigneImpl
   * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getLigne()
   * @generated
   */
  int LIGNE = 1;

  /**
   * The number of structural features of the '<em>Ligne</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.fil2018.flomira.suricate.impl.AffectationImpl <em>Affectation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.fil2018.flomira.suricate.impl.AffectationImpl
   * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getAffectation()
   * @generated
   */
  int AFFECTATION = 2;

  /**
   * The feature id for the '<em><b>Obj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__OBJ = LIGNE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__VAR = LIGNE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Affectation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION_FEATURE_COUNT = LIGNE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.fil2018.flomira.suricate.impl.ParametreImpl <em>Parametre</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.fil2018.flomira.suricate.impl.ParametreImpl
   * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getParametre()
   * @generated
   */
  int PARAMETRE = 10;

  /**
   * The number of structural features of the '<em>Parametre</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETRE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.fil2018.flomira.suricate.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.fil2018.flomira.suricate.impl.VariableImpl
   * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = PARAMETRE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = PARAMETRE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.fil2018.flomira.suricate.impl.ObjetImpl <em>Objet</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.fil2018.flomira.suricate.impl.ObjetImpl
   * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getObjet()
   * @generated
   */
  int OBJET = 4;

  /**
   * The number of structural features of the '<em>Objet</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_FEATURE_COUNT = PARAMETRE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.fil2018.flomira.suricate.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.fil2018.flomira.suricate.impl.IntLiteralImpl
   * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__NAME = OBJET_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = OBJET_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.fil2018.flomira.suricate.impl.StringLiteralImpl <em>String Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.fil2018.flomira.suricate.impl.StringLiteralImpl
   * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getStringLiteral()
   * @generated
   */
  int STRING_LITERAL = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL__NAME = OBJET_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL_FEATURE_COUNT = OBJET_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.fil2018.flomira.suricate.impl.ConstructeurImpl <em>Constructeur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.fil2018.flomira.suricate.impl.ConstructeurImpl
   * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getConstructeur()
   * @generated
   */
  int CONSTRUCTEUR = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRUCTEUR__NAME = OBJET_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Constructeur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRUCTEUR_FEATURE_COUNT = OBJET_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.fil2018.flomira.suricate.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.fil2018.flomira.suricate.impl.OperationImpl
   * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__NAME = LIGNE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Methode</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__METHODE = LIGNE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = LIGNE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.fil2018.flomira.suricate.impl.MethodeImpl <em>Methode</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.fil2018.flomira.suricate.impl.MethodeImpl
   * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getMethode()
   * @generated
   */
  int METHODE = 9;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHODE__PARAMS = 0;

  /**
   * The number of structural features of the '<em>Methode</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHODE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.fil2018.flomira.suricate.Programme <em>Programme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Programme</em>'.
   * @see org.fil2018.flomira.suricate.Programme
   * @generated
   */
  EClass getProgramme();

  /**
   * Returns the meta object for the containment reference list '{@link org.fil2018.flomira.suricate.Programme#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.fil2018.flomira.suricate.Programme#getElements()
   * @see #getProgramme()
   * @generated
   */
  EReference getProgramme_Elements();

  /**
   * Returns the meta object for class '{@link org.fil2018.flomira.suricate.Ligne <em>Ligne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ligne</em>'.
   * @see org.fil2018.flomira.suricate.Ligne
   * @generated
   */
  EClass getLigne();

  /**
   * Returns the meta object for class '{@link org.fil2018.flomira.suricate.Affectation <em>Affectation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Affectation</em>'.
   * @see org.fil2018.flomira.suricate.Affectation
   * @generated
   */
  EClass getAffectation();

  /**
   * Returns the meta object for the containment reference '{@link org.fil2018.flomira.suricate.Affectation#getObj <em>Obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Obj</em>'.
   * @see org.fil2018.flomira.suricate.Affectation#getObj()
   * @see #getAffectation()
   * @generated
   */
  EReference getAffectation_Obj();

  /**
   * Returns the meta object for the containment reference '{@link org.fil2018.flomira.suricate.Affectation#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see org.fil2018.flomira.suricate.Affectation#getVar()
   * @see #getAffectation()
   * @generated
   */
  EReference getAffectation_Var();

  /**
   * Returns the meta object for class '{@link org.fil2018.flomira.suricate.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.fil2018.flomira.suricate.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.fil2018.flomira.suricate.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.fil2018.flomira.suricate.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link org.fil2018.flomira.suricate.Objet <em>Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Objet</em>'.
   * @see org.fil2018.flomira.suricate.Objet
   * @generated
   */
  EClass getObjet();

  /**
   * Returns the meta object for class '{@link org.fil2018.flomira.suricate.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see org.fil2018.flomira.suricate.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link org.fil2018.flomira.suricate.IntLiteral#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.fil2018.flomira.suricate.IntLiteral#getName()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Name();

  /**
   * Returns the meta object for class '{@link org.fil2018.flomira.suricate.StringLiteral <em>String Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Literal</em>'.
   * @see org.fil2018.flomira.suricate.StringLiteral
   * @generated
   */
  EClass getStringLiteral();

  /**
   * Returns the meta object for the attribute '{@link org.fil2018.flomira.suricate.StringLiteral#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.fil2018.flomira.suricate.StringLiteral#getName()
   * @see #getStringLiteral()
   * @generated
   */
  EAttribute getStringLiteral_Name();

  /**
   * Returns the meta object for class '{@link org.fil2018.flomira.suricate.Constructeur <em>Constructeur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constructeur</em>'.
   * @see org.fil2018.flomira.suricate.Constructeur
   * @generated
   */
  EClass getConstructeur();

  /**
   * Returns the meta object for the attribute '{@link org.fil2018.flomira.suricate.Constructeur#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.fil2018.flomira.suricate.Constructeur#getName()
   * @see #getConstructeur()
   * @generated
   */
  EAttribute getConstructeur_Name();

  /**
   * Returns the meta object for class '{@link org.fil2018.flomira.suricate.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.fil2018.flomira.suricate.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for the reference '{@link org.fil2018.flomira.suricate.Operation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see org.fil2018.flomira.suricate.Operation#getName()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.fil2018.flomira.suricate.Operation#getMethode <em>Methode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Methode</em>'.
   * @see org.fil2018.flomira.suricate.Operation#getMethode()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Methode();

  /**
   * Returns the meta object for class '{@link org.fil2018.flomira.suricate.Methode <em>Methode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Methode</em>'.
   * @see org.fil2018.flomira.suricate.Methode
   * @generated
   */
  EClass getMethode();

  /**
   * Returns the meta object for the containment reference list '{@link org.fil2018.flomira.suricate.Methode#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see org.fil2018.flomira.suricate.Methode#getParams()
   * @see #getMethode()
   * @generated
   */
  EReference getMethode_Params();

  /**
   * Returns the meta object for class '{@link org.fil2018.flomira.suricate.Parametre <em>Parametre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parametre</em>'.
   * @see org.fil2018.flomira.suricate.Parametre
   * @generated
   */
  EClass getParametre();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SuricateFactory getSuricateFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.fil2018.flomira.suricate.impl.ProgrammeImpl <em>Programme</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.fil2018.flomira.suricate.impl.ProgrammeImpl
     * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getProgramme()
     * @generated
     */
    EClass PROGRAMME = eINSTANCE.getProgramme();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMME__ELEMENTS = eINSTANCE.getProgramme_Elements();

    /**
     * The meta object literal for the '{@link org.fil2018.flomira.suricate.impl.LigneImpl <em>Ligne</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.fil2018.flomira.suricate.impl.LigneImpl
     * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getLigne()
     * @generated
     */
    EClass LIGNE = eINSTANCE.getLigne();

    /**
     * The meta object literal for the '{@link org.fil2018.flomira.suricate.impl.AffectationImpl <em>Affectation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.fil2018.flomira.suricate.impl.AffectationImpl
     * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getAffectation()
     * @generated
     */
    EClass AFFECTATION = eINSTANCE.getAffectation();

    /**
     * The meta object literal for the '<em><b>Obj</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFFECTATION__OBJ = eINSTANCE.getAffectation_Obj();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFFECTATION__VAR = eINSTANCE.getAffectation_Var();

    /**
     * The meta object literal for the '{@link org.fil2018.flomira.suricate.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.fil2018.flomira.suricate.impl.VariableImpl
     * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link org.fil2018.flomira.suricate.impl.ObjetImpl <em>Objet</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.fil2018.flomira.suricate.impl.ObjetImpl
     * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getObjet()
     * @generated
     */
    EClass OBJET = eINSTANCE.getObjet();

    /**
     * The meta object literal for the '{@link org.fil2018.flomira.suricate.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.fil2018.flomira.suricate.impl.IntLiteralImpl
     * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__NAME = eINSTANCE.getIntLiteral_Name();

    /**
     * The meta object literal for the '{@link org.fil2018.flomira.suricate.impl.StringLiteralImpl <em>String Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.fil2018.flomira.suricate.impl.StringLiteralImpl
     * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getStringLiteral()
     * @generated
     */
    EClass STRING_LITERAL = eINSTANCE.getStringLiteral();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_LITERAL__NAME = eINSTANCE.getStringLiteral_Name();

    /**
     * The meta object literal for the '{@link org.fil2018.flomira.suricate.impl.ConstructeurImpl <em>Constructeur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.fil2018.flomira.suricate.impl.ConstructeurImpl
     * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getConstructeur()
     * @generated
     */
    EClass CONSTRUCTEUR = eINSTANCE.getConstructeur();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTRUCTEUR__NAME = eINSTANCE.getConstructeur_Name();

    /**
     * The meta object literal for the '{@link org.fil2018.flomira.suricate.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.fil2018.flomira.suricate.impl.OperationImpl
     * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__NAME = eINSTANCE.getOperation_Name();

    /**
     * The meta object literal for the '<em><b>Methode</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__METHODE = eINSTANCE.getOperation_Methode();

    /**
     * The meta object literal for the '{@link org.fil2018.flomira.suricate.impl.MethodeImpl <em>Methode</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.fil2018.flomira.suricate.impl.MethodeImpl
     * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getMethode()
     * @generated
     */
    EClass METHODE = eINSTANCE.getMethode();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHODE__PARAMS = eINSTANCE.getMethode_Params();

    /**
     * The meta object literal for the '{@link org.fil2018.flomira.suricate.impl.ParametreImpl <em>Parametre</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.fil2018.flomira.suricate.impl.ParametreImpl
     * @see org.fil2018.flomira.suricate.impl.SuricatePackageImpl#getParametre()
     * @generated
     */
    EClass PARAMETRE = eINSTANCE.getParametre();

  }

} //SuricatePackage
