/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.ide;

import org.fil2018.flomira.ide.AbstractSuricateIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SuricateIdeModule extends AbstractSuricateIdeModule {
}
