/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SuricateIdeModule /* implements AbstractSuricateIdeModule  */{
}
