/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.ide;

import com.google.inject.Injector;
import org.fil2018.flomira.SuricateStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SuricateIdeSetup extends SuricateStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from SuricateIdeModule to Module");
  }
}
