/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.fil2018.flomira.SuricateRuntimeModule;
import org.fil2018.flomira.SuricateStandaloneSetup;
import org.fil2018.flomira.ide.SuricateIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SuricateIdeSetup extends SuricateStandaloneSetup {
  @Override
  public Injector createInjector() {
    SuricateRuntimeModule _suricateRuntimeModule = new SuricateRuntimeModule();
    SuricateIdeModule _suricateIdeModule = new SuricateIdeModule();
    return Guice.createInjector(Modules2.mixin(_suricateRuntimeModule, _suricateIdeModule));
  }
}
