/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.suricate.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.fil2018.flomira.suricate.AppelMethSimple;
import org.fil2018.flomira.suricate.Parametre;
import org.fil2018.flomira.suricate.SuricatePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Appel Meth Simple</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.fil2018.flomira.suricate.impl.AppelMethSimpleImpl#getMethodeName <em>Methode Name</em>}</li>
 *   <li>{@link org.fil2018.flomira.suricate.impl.AppelMethSimpleImpl#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AppelMethSimpleImpl extends MinimalEObjectImpl.Container implements AppelMethSimple
{
  /**
   * The default value of the '{@link #getMethodeName() <em>Methode Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMethodeName()
   * @generated
   * @ordered
   */
  protected static final String METHODE_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMethodeName() <em>Methode Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMethodeName()
   * @generated
   * @ordered
   */
  protected String methodeName = METHODE_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getParams() <em>Params</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParams()
   * @generated
   * @ordered
   */
  protected EList<Parametre> params;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AppelMethSimpleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SuricatePackage.Literals.APPEL_METH_SIMPLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getMethodeName()
  {
    return methodeName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMethodeName(String newMethodeName)
  {
    String oldMethodeName = methodeName;
    methodeName = newMethodeName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SuricatePackage.APPEL_METH_SIMPLE__METHODE_NAME, oldMethodeName, methodeName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Parametre> getParams()
  {
    if (params == null)
    {
      params = new EObjectContainmentEList<Parametre>(Parametre.class, this, SuricatePackage.APPEL_METH_SIMPLE__PARAMS);
    }
    return params;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SuricatePackage.APPEL_METH_SIMPLE__PARAMS:
        return ((InternalEList<?>)getParams()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SuricatePackage.APPEL_METH_SIMPLE__METHODE_NAME:
        return getMethodeName();
      case SuricatePackage.APPEL_METH_SIMPLE__PARAMS:
        return getParams();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SuricatePackage.APPEL_METH_SIMPLE__METHODE_NAME:
        setMethodeName((String)newValue);
        return;
      case SuricatePackage.APPEL_METH_SIMPLE__PARAMS:
        getParams().clear();
        getParams().addAll((Collection<? extends Parametre>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SuricatePackage.APPEL_METH_SIMPLE__METHODE_NAME:
        setMethodeName(METHODE_NAME_EDEFAULT);
        return;
      case SuricatePackage.APPEL_METH_SIMPLE__PARAMS:
        getParams().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SuricatePackage.APPEL_METH_SIMPLE__METHODE_NAME:
        return METHODE_NAME_EDEFAULT == null ? methodeName != null : !METHODE_NAME_EDEFAULT.equals(methodeName);
      case SuricatePackage.APPEL_METH_SIMPLE__PARAMS:
        return params != null && !params.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (methodeName: ");
    result.append(methodeName);
    result.append(')');
    return result.toString();
  }

} //AppelMethSimpleImpl
