/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.suricate.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.fil2018.flomira.suricate.Boucle;
import org.fil2018.flomira.suricate.SuricatePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Boucle</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BoucleImpl extends MinimalEObjectImpl.Container implements Boucle
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BoucleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SuricatePackage.Literals.BOUCLE;
  }

} //BoucleImpl
