/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.suricate.impl;

import org.eclipse.emf.ecore.EClass;

import org.fil2018.flomira.suricate.IfBoucle;
import org.fil2018.flomira.suricate.SuricatePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>If Boucle</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IfBoucleImpl extends BoucleImpl implements IfBoucle
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IfBoucleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SuricatePackage.Literals.IF_BOUCLE;
  }

} //IfBoucleImpl
