/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira;

import org.fil2018.flomira.SuricateStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SuricateStandaloneSetup extends SuricateStandaloneSetupGenerated {
  public static void doSetup() {
    new SuricateStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
