/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira;

import org.fil2018.flomira.AbstractSuricateRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SuricateRuntimeModule extends AbstractSuricateRuntimeModule {
}
