/*
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SuricateRuntimeModule extends AbstractSuricateRuntimeModule {
}
