/*
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSuricateScopeProvider extends DelegatingScopeProvider {
}
