/*
 * generated by Xtext 2.10.0
 */
package org.fil2018.flomira.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.fil2018.flomira.ide.contentassist.antlr.internal.InternalSuricateParser;
import org.fil2018.flomira.services.SuricateGrammarAccess;

public class SuricateParser extends AbstractContentAssistParser {

	@Inject
	private SuricateGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalSuricateParser createParser() {
		InternalSuricateParser result = new InternalSuricateParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getLigneAccess().getAlternatives(), "rule__Ligne__Alternatives");
					put(grammarAccess.getObjetAccess().getAlternatives(), "rule__Objet__Alternatives");
					put(grammarAccess.getParametreAccess().getAlternatives(), "rule__Parametre__Alternatives");
					put(grammarAccess.getAffectationAccess().getGroup(), "rule__Affectation__Group__0");
					put(grammarAccess.getConstructeurAccess().getGroup(), "rule__Constructeur__Group__0");
					put(grammarAccess.getOperationAccess().getGroup(), "rule__Operation__Group__0");
					put(grammarAccess.getMethodeAccess().getGroup(), "rule__Methode__Group__0");
					put(grammarAccess.getMethodeAccess().getGroup_3(), "rule__Methode__Group_3__0");
					put(grammarAccess.getMethodeAccess().getGroup_3_1(), "rule__Methode__Group_3_1__0");
					put(grammarAccess.getProgrammeAccess().getElementsAssignment(), "rule__Programme__ElementsAssignment");
					put(grammarAccess.getAffectationAccess().getObjAssignment_1(), "rule__Affectation__ObjAssignment_1");
					put(grammarAccess.getAffectationAccess().getVarAssignment_3(), "rule__Affectation__VarAssignment_3");
					put(grammarAccess.getVariableAccess().getNameAssignment(), "rule__Variable__NameAssignment");
					put(grammarAccess.getIntLiteralAccess().getNameAssignment(), "rule__IntLiteral__NameAssignment");
					put(grammarAccess.getStringLiteralAccess().getNameAssignment(), "rule__StringLiteral__NameAssignment");
					put(grammarAccess.getConstructeurAccess().getNameAssignment_0(), "rule__Constructeur__NameAssignment_0");
					put(grammarAccess.getOperationAccess().getNameAssignment_0(), "rule__Operation__NameAssignment_0");
					put(grammarAccess.getOperationAccess().getMethodeAssignment_2(), "rule__Operation__MethodeAssignment_2");
					put(grammarAccess.getMethodeAccess().getParamsAssignment_3_0(), "rule__Methode__ParamsAssignment_3_0");
					put(grammarAccess.getMethodeAccess().getParamsAssignment_3_1_1(), "rule__Methode__ParamsAssignment_3_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalSuricateParser typedParser = (InternalSuricateParser) parser;
			typedParser.entryRuleProgramme();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SuricateGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SuricateGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
