/**
 * generated by Xtext 2.12.0
 */
package org.fil2018.flomira.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.fil2018.flomira.ui.AbstractSuricateUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SuricateUiModule extends AbstractSuricateUiModule {
  public SuricateUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
